config/routes.rb
Rails.application.routes.draw do

  root "blogs#index"

  resources :blogs, only:[:index] do
    collection do
      post 'upload_img'
      get 'set'
      post 'set_userinfo'
      get 'set_blog'
      post 'update_blog'
      get 'about'
      get 'change_password'
      post 'update_password'
      post 'preview'
    end

  end

  resources :articles do
    member do
      post 'star'
    end

    resources :comments
  end

  get 'register' => 'users#register'
  get 'login' => 'users#login'
  get 'logout' => 'users#logout'
  resources :users do
    collection do
      get 'register'
      post 'register_confirm'
      get 'login'
      post 'login_confirm'
      get 'logout'
      get 'send_active_mail'
      get 'activation'
      get 'forget_password'
      post 'forget_password_confirm'
      get 'change_pw'
      post 'change_pw_confirm'
    end
  end

end

app/models/article.rb
#encoding: utf-8
class Article < ActiveRecord::Base
  attr_accessor :category_name
  belongs_to :category, counter_cache: 'articles_count'
  belongs_to :user
  has_many :article_stars
  has_many :article_views
  has_many :comments, class_name: 'ArticleComment'

  validates :title, length: {minimum: 10, maximum: 50}
  validates :tags, presence: true
  validates :source, allow_blank: true, format: {with: /[a-zA-Z0-9-]+\.[a-zA-Z0-9]+/}
  validates :content, length: {minimum: 10}

  validate :validate_category

  def validate_category
    errors.add(:category_id, '分类不正确') unless Category.find(self.category_id)
  rescue
    errors.add(:category_id, '分类不正确')
    return false
  else
    return true
  end

  def add_view(ip, current_user, param_string)
    return false if (self.article_views.where("created_at >= '#{DateTime.now - 10.minute}' and ip='#{ip}'").count > 0)
    view = self.article_views.new ip: ip, param_string: param_string
    view.user_id = current_user.id if current_user
    view.save
  end

end

app/models/article_view.rb
#encoding: utf-8
class ArticleView < ActiveRecord::Base
  belongs_to :article, counter_cache: 'view_count'

end

app/controllers/articles_controller.rb
#encoding: utf-8
class ArticlesController < ApplicationController
  before_filter :check_current_user_is_admin, only: [:new, :create, :edit, :update]
  before_filter :article, only: [:show, :edit, :update, :destroy, :star]

  def index
    res = Article
    order = 'updated_at desc'
    if params[:sort].present?
      order = case params[:sort]
                when 'star'
                  'star_count desc'
                when 'comments'
                  'comments_count desc'
                else
                  'updated_at desc'
              end
    end
    if params[:c].present?
      category = Category.find params[:c]
      res = res.where("category_id=#{category.id}") if category
    end
    res = res.where("title like ?", "%#{params[:keyword]}%") if params[:keyword].present?
    @articles = res.order(order).page(params[:page]).per(Settings.blog.aritcle_page_size)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new params.require(:article).permit(:title, :tags, :source, :content)
    @article.user_id = @current_user.id
    if params[:article].present? && params[:article][:category_id].present?
      @article.category_id = params[:article][:category_id]
    elsif params[:article].present? && params[:article][:category_name].present?
      category = Category.find_or_create params[:article][:category_name]
      @article.category_id = category.id
    end
    if @article.save
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @article.add_view request.remote_ip, @current_user, params.inspect
    @comment = @article.comments.new
    @comments = @article.comments.order('updated_at asc').page(params[:page]).per(Settings.blog.comments_page_size)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit

  end

  def update
    attributes = params.require(:article).permit(:title, :tags, :source, :content)
    if params[:article].present? && params[:article][:category_id].present?
      attributes[:category_id] = params[:article][:category_id]
    elsif params[:article].present? && params[:article][:category_name].present?
      category = Category.find_or_create params[:article][:category_name]
      attributes[:category_id] = category.id
    end
    if @article.update_attributes attributes
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path
    else
      flash[:error] = '删除失败'
      redirect_to article_path(@article)
    end
  end

  def star
    if current_user_can_star? @article
      @result = {status: false, message: '', star_count: 0}
      star = @article.article_stars.new user_id: @current_user.id
      if star.save
        @result[:star_count] = (@article.star_count || 0) + 1
        @result[:status] = true
      else
        @result[:message] = '称赞失败'
      end
      respond_to do |format|
        format.js
      end
    end
  end

  protected

  def check_current_user_is_admin
   redirect_to root_path unless (@current_user && @current_user.admin)
  end

  def article
    @article = Article.find params[:id]
  end
end

app/views/articles/_article.html.haml
.article_content
  %h3
    - if article.source.empty?
      [原创]
    = link_to article.title, article_path(article), target: '_blank'
  - get_tags(article).each do |tag|
    %span.label.label-default
      = tag
  %p
    %span.icon.icon-time(data-toggle="tooltip" data-placement="bottom" title="发表时间")
      = article.updated_at.strftime('%Y-%m-%d')
    %span.icon.icon-eye-open(data-toggle="tooltip" data-placement="bottom" title="浏览数")
      = article.view_count || 0
    %span.icon.icon-thumbs-up(data-toggle="tooltip" data-placement="bottom" title="称赞数")
      = article.star_count || 0
    %span.icon.icon-comments(data-toggle="tooltip" data-placement="bottom" title="评论数")
      = article.comments_count || 0
  - unless article.source.empty?
    %p
      转载：
      = article.source

  .row-fluid.article_des
    %p
      = article.content[0..300]

app/views/articles/_article_sidebar.html.haml
.text-left.ui-sortable
  %h4 文章分类
  %ul.nav.bs-docs-sidenav
    %li
      = link_to articles_path, remote: true do
        全部
        %span.badge
          = "#{get_articles_count}篇"
    - get_categories.each do |category|
      %li
        = link_to articles_path(c: category.id), remote: true do
          = category.name
          %span.badge
            = "#{category.articles_count || 0}篇"

app/views/articles/_articles.html.haml
- unless @articles.present?
  .jumbotron
    %h2 什么也没有～
- @articles.each do |article|
  = render partial: 'articles/article', locals: {article: article}

= paginate @articles, remote: true if params[:controller] == 'articles'

app/views/articles/_comment.html.haml
.panel.panel-dfault{id: "comment_#{comment.id}"}
  .panel-body
    .row
      .col-md-1.text-center
        %span.comment_avatar
          = avatar comment.user
        = comment.user.nickname
      .comment_content.col-md-9{id: "comment_#{comment.id}_body"}
        = raw sanitize(markdown_parser(comment.content))
    .row.comment_footer.text-right
      %span.icon.icon-time(data-toggle="tooltip" data-placement="bottom" title="评论时间")
        = "#{comment.updated_at.strftime('%Y-%m-%d %H:%M:%S')}"
      - if current_user_can_edit_comment?(comment)
        = link_to edit_article_comment_path(@article, comment), remote: true do
          %span.icon.icon-edit
      - if current_user_is_admin? || current_user_can_edit_comment?(comment)
        = link_to article_comment_path(@article, comment), method: 'delete', remote: true, "data-confirm"=> '确定删除吗？' do
          %span.icon.icon-trash

app/views/articles/_comment_form.html.haml
= render partial: 'articles/toolbar_upload_img', locals: {text_id: 'article_comment_content'}
- if defined?(new_comment) && new_comment
  - @comment = @article.comments.new
.comment_form
  - url = @comment.new_record? ? article_comments_path(@article) : article_comment_path(@article, @comment)
  = form_for @comment, url: url, role: 'form', remote: true do |f|
    .error#error_message
    .form-group
      %ul.nav.nav-tabs#preview_tab{role: "tablist"}
        %li.active
          = link_to (@comment.new_record? ? '发表评论' : '编辑评论'), '#edit', role: 'tab', 'data-toggle'=>'tab'
        %li
          = link_to '预览', '#preview', role: 'tab', 'data-toggle'=>'tab'
      .tab-content
        .tab-pane.active#edit
          = f.text_area :content, placeholder: '评论内容', class: 'form-control'
        .tab-pane#preview
    .form-group
      = f.submit '提交', class: 'btn btn-success btn-lg btn-block'

:javascript
  $(function(){
    $('#preview_tab a[href="#preview"]').click(function(e){
      e.preventDefault();
      $(this).tab('show');
      preview('article_comment_content', 'preview');
    });
  });

app/views/articles/_comments.html.haml
- unless @comments.present?
  .jumbotron#no_comments
    %h2 还没有评论～
- @comments.each do |comment|
  = render partial: 'comment', locals: {comment: comment}
#paginate
  = paginate @comments, remote: true

app/views/articles/_error.html.haml
- errors = @article.errors.full_messages
- if errors.any?
  .alert.alert-danger
    %a.close{"data-dismiss"=>"alert"} &times;
    %span
      = errors.first
- elsif flash[:error].present?
  .alert.alert-danger
    %a.close{"data-dismiss"=>"alert"} &times;
    %span
      = flash[:error]

app/views/articles/_form.html.haml
= render partial: 'toolbar_upload_img', locals: {text_id: 'article_content'}

= form_for @article, role: 'form' do |f|
  .form-group
    %label{for: 'article_title'} 文章标题
    = f.text_field :title, placeholder: '文章标题', class: 'form-control'
  .form-group
    %label{for: 'article_category_id'} 文章分类
    = select_tag "article[category_id]", options_for_select(get_categories_options, @article.category_id), include_blank: true, class: 'form-control'
    或者新建一个分类：
    = f.text_field :category_name, placeholder: '分类名称', class: 'form-control'
  .form-group
    %label{for: 'article_tags'} 标签
    = f.text_field :tags, placeholder: '文章标签，多个用英文“,”隔开', class: 'form-control'
  .form-group
    %label{for: 'article_source'} 文章来源
    = f.text_field :source, placeholder: '文章来源，为空则为原创', class: 'form-control'
  .form-group
    %ul.nav.nav-tabs#preview_tab{role: "tablist"}
      %li.active
        = link_to '文章内容', '#edit', role: 'tab', 'data-toggle'=>'tab'
      %li
        = link_to '预览', '#preview', role: 'tab', 'data-toggle'=>'tab'
    .tab-content
      .tab-pane.active#edit
        = f.text_area :content, placeholder: '文章内容', class: 'form-control'
      .tab-pane#preview
  .form-group
    = f.submit '提交', class: 'btn btn-success btn-lg btn-block'

:javascript
  $(function(){
    $('#preview_tab a[href="#preview"]').click(function(e){
      e.preventDefault();
      $(this).tab('show');
      preview('article_content', 'preview');
    });
  });

app/views/articles/_toolbar_upload_img.html.haml
= form_for :upload, url: upload_img_blogs_path, enctype: "multipart/form-data", class: 'form-horizontal', role: 'form', remote: true do |f|
  .modal.fade#upload_modal
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss"=>"modal"}
            %span{"aria-hidden"=>"true"}
              &times;
            %span.sr-only
              Close
          %h4 上传图片
        .modal-body
          .form-group.row.text-center
            .error.text-center#error
            %label.col-sm-2.control-label.text-right{for: "upload_img"} 图片：
            .col-sm-8.text-left
              = token_tag
              = f.hidden_field :text_id, value: text_id
              = f.file_field :img
        .modal-footer
          %button.btn.btn-default{"data-dismiss"=>"modal"} 关闭
          = submit_tag '上传', class: 'btn btn-primary'


:javascript
  $(function(){
    new MarkdownToolbar($('##{text_id}'));
    $('.mdt_button_image').unbind('click');
    $('.mdt_button_image').click(function(){
      $('#upload_modal').modal('show');
    });
  });

app/views/articles/edit.html.haml
%h3 编辑博文
= render partial: 'error'
= render partial: 'form'

app/views/articles/index.html.haml
.row.inner.edge
  .col-md-9.layout-main
    .tab-nav
    -#  %h2.common-title 博文列表
    %nav.sub-tab.row
      %span.col-md-6.text-left
        %h3 文章列表
      %span.col-md-6.text-right.sort_navbar
        - params_hash = params.dup
        - params_hash.delete :page
        %span.icon.icon-circle-arrow-down(data-toggle="tooltip" data-placement="bottom" title="排序")
        = link_to '按时间', articles_path(params_hash.merge({sort: 'time'})), remote: true, class: "#{'current' if params[:sort].nil? || params[:sort] == 'time'}"
        = link_to '按称赞', articles_path(params_hash.merge({sort: 'star'})), remote: true, class: "#{'current' if params[:sort].present? && params[:sort] == 'star'}"
        = link_to '按评论', articles_path(params_hash.merge({sort: 'comments'})), remote: true, class: "#{'current' if params[:sort].present? && params[:sort] == 'comments'}"
    .article-list#article-list
      = render partial: 'articles'

  .sidebar.col-md-3.layout-secondary.hidden-xs.hidden-sm
    = render partial: 'article_sidebar'

:javascript
  $(function(){
    $('.sort_navbar a').click(function(){
      $(this).addClass('current').siblings().removeClass('current');
    });
  });

app/views/articles/new.html.haml
%h3 撰写博文
= render partial: 'error'
= render partial: 'form'

app/views/articles/show.html.haml
.article_show
  = render partial: 'error'
  %h3.article-title
    - if @article.source.empty?
      [原创]
    = @article.title
    - if current_user_is_admin?
      = link_to edit_article_path(@article) do
        %span.icon.icon-edit
      = link_to article_path(@article), method: 'delete', "data-confirm"=> "确定删除吗？" do
        %span.icon.icon-trash


  %p
    - get_tags(@article).each do |tag|
      %span.label.label-default
        = tag
  %p
    %span.icon
      分类：
      = link_to @article.category.name, articles_path(c: @article.category_id)
    %span.icon.icon-time(data-toggle="tooltip" data-placement="bottom" title="发表时间")
      = @article.updated_at.strftime('%Y-%m-%d %H:%M')
    %span.icon.icon-eye-open(data-toggle="tooltip" data-placement="bottom" title="浏览")
      = @article.view_count || 1
    - if current_user_can_star?(@article)
      = link_to star_article_path(@article), method: :post, remote: 'true' do
        %span.icon.icon-thumbs-up#article_star(data-toggle="tooltip" data-placement="bottom" title="称赞")
          = @article.star_count || 0
    - else
      %span.icon.icon-thumbs-up(data-toggle="tooltip" data-placement="bottom" title="称赞数")
        = @article.star_count || 0
    %span.icon.icon-comments(data-toggle="tooltip" data-placement="bottom" title="评论")
      = @article.comments_count || 0
    %span
      = social_share_button_tag(@article.title)
  - unless @article.source.empty?
    %p
      转载：
      = @article.source

  .panel.panel-dfault
    .panel-body#article_content_show
      -#= raw markdown_parser(@article.content)

  %h3 评论：
  #comments_content
    = render partial: 'comments'

  - if is_logined?
    #comment_form
      = render partial: 'comment_form'
  - else
    .jumbotron
      %h2
        = link_to '登录', login_path
        后可评论

:javascript
  $(function(){
    $('#article_content_show').html("#{escape_javascript sanitize(markdown_parser(@article.content))}");
  });

app/views/articles/star.js.haml
- if @result[:status]
  :plain
    $('#article_star').html(" #{@result[:star_count]}");
    $('#article_star').parent('a').attr('href', 'javascript:void(0);').addClass('disabled');